#include "payload/manifest.json.h"
#include "payload/static/css/main.c83abc47.css.h"
#include "payload/static/js/main.12f95d7e.js.h"
#include "payload/static/js/787.05b7a068.chunk.js.h"
#include "payload/index.html.h"

#define MANIFEST_JSON_PATH "/RGB-strip-controller/manifest.json"
#define MAIN_JS_PATH "/RGB-strip-controller/static/css/main.c83abc47.css"
#define MAIN_CSS_PATH "/RGB-strip-controller/static/js/main.12f95d7e.js"
#define CHUNK_JS_PATH "/RGB-strip-controller/static/js/787.05b7a068.chunk.js"
#define INDEX_HTML_PATH "/RGB-strip-controller/index.html"